name: Sample Pipeline
on: [push]
jobs:
  My First Pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run: |
        echo "Hello Pipeline"
        ls -la 
        cat /etc/proc