name: Sample Pipeline
on: 
  push:
   branches:
   - dev
jobs:
  MyFirstPipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run: |
        echo "Hello Pipeline"
        ls -la 